<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.


/**
 * Core external functions and service definitions.
 *
 * The functions and services defined on this file are
 * processed and registered into the Moodle DB after any
 * install or upgrade operation. All plugins support this.
 *
 * For more information, take a look to the documentation available:
 *     - Webservices API: {@link https://moodledev.io/docs/apis/subsystems/external/writing-a-service}
 *     - External API: {@link https://moodledev.io/docs/apis/subsystems/external/functions}
 *     - Upgrade API: {@link https://moodledev.io/docs/guides/upgrade}
 *
 * @package    core_webservice
 * @category   webservice
 * @copyright  2009 Petr Skodak
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

$functions = array(
    'core_auth_confirm_user' => array(
        'classname'   => 'core_auth_external',
        'methodname'  => 'confirm_user',
        'description' => 'Confirm a user account.',
        'type'        => 'write',
        'ajax'          => true,
        'loginrequired' => false,
    ),
    'core_auth_request_password_reset' => array(
        'classname'   => 'core_auth_external',
        'methodname'  => 'request_password_reset',
        'description' => 'Requests a password reset.',
        'type'        => 'write',
        'ajax'          => true,
        'loginrequired' => false,
    ),
    'core_auth_is_minor' => array(
        'classname'   => 'core_auth_external',
        'methodname'  => 'is_minor',
        'description' => 'Requests a check if a user is a digital minor.',
        'type'        => 'read',
        'ajax'          => true,
        'loginrequired' => false,
    ),
    'core_auth_is_age_digital_consent_verification_enabled' => array(
        'classname'   => 'core_auth_external',
        'methodname'  => 'is_age_digital_consent_verification_enabled',
        'description' => 'Checks if age digital consent verification is enabled.',
        'type'        => 'read',
        'ajax'          => true,
        'loginrequired' => false,
    ),
    'core_auth_resend_confirmation_email' => array(
        'classname'   => 'core_auth_external',
        'methodname'  => 'resend_confirmation_email',
        'description' => 'Resend confirmation email.',
        'type'        => 'write',
        'ajax'          => true,
        'loginrequired' => false,
    ),
    ],
    ),
    ],
    'core_blog_get_entries' => array(
        'classname'   => 'core_blog\external',
        'methodname'  => 'get_entries',
        'description' => 'Returns blog entries.',
        'type'        => 'read',
        'services'    => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'ajax'          => true,
        'loginrequired' => false,
    ),
    'core_blog_view_entries' => array(
        'classname'   => 'core_blog\external',
        'methodname'  => 'view_entries',
        'description' => 'Trigger the blog_entries_viewed event.',
        'type'        => 'read',
        'services'    => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'ajax'          => true,
        'loginrequired' => false,
    ),
    'core_blog_get_access_information' => [
        'classname' => '\core_blog\external\get_access_information',
        'description' => 'Retrieves permission information for the current user.',
        'type' => 'read',
        'services' => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'core_blog_add_entry' => [
        'classname' => '\core_blog\external\add_entry',
        'description' => 'Creates a new blog post entry.',
        'type' => 'write',
        'services' => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'core_blog_delete_entry' => [
        'classname' => '\core_blog\external\delete_entry',
        'description' => 'Deletes a blog post entry.',
        'type' => 'write',
        'services' => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'core_blog_prepare_entry_for_edition' => [
        'classname' => '\core_blog\external\prepare_entry_for_edition',
        'description' => 'Prepare a draft area for editing a blog entry..',
        'type' => 'write',
        'services' => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'core_blog_update_entry' => [
        'classname' => '\core_blog\external\update_entry',
        'description' => 'Updates a blog entry.',
        'type' => 'write',
        'services' => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'core_calendar_get_calendar_monthly_view' => array(
        'classname' => 'core_calendar_external',
        'methodname' => 'get_calendar_monthly_view',
        'description' => 'Fetch the monthly view data for a calendar',
        'classpath' => 'calendar/externallib.php',
        'type' => 'read',
        'capabilities' => '',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_calendar_get_calendar_day_view' => array(
        'classname' => 'core_calendar_external',
        'methodname' => 'get_calendar_day_view',
        'description' => 'Fetch the day view data for a calendar',
        'classpath' => 'calendar/externallib.php',
        'type' => 'read',
        'capabilities' => '',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_calendar_get_calendar_upcoming_view' => array(
        'classname' => 'core_calendar_external',
        'methodname' => 'get_calendar_upcoming_view',
        'description' => 'Fetch the upcoming view data for a calendar',
        'classpath' => 'calendar/externallib.php',
        'type' => 'read',
        'capabilities' => '',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_calendar_update_event_start_day' => array(
        'classname' => 'core_calendar_external',
        'methodname' => 'update_event_start_day',
        'description' => 'Update the start day (but not time) for an event.',
        'classpath' => 'calendar/externallib.php',
        'type' => 'write',
        'capabilities' => 'moodle/calendar:manageentries, moodle/calendar:manageownentries, moodle/calendar:managegroupentries',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_calendar_create_calendar_events' => array(
        'classname' => 'core_calendar_external',
        'methodname' => 'create_calendar_events',
        'description' => 'Create calendar events',
        'classpath' => 'calendar/externallib.php',
        'type' => 'write',
        'capabilities' => 'moodle/calendar:manageentries, moodle/calendar:manageownentries, moodle/calendar:managegroupentries',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_calendar_delete_calendar_events' => array(
        'classname' => 'core_calendar_external',
        'methodname' => 'delete_calendar_events',
        'description' => 'Delete calendar events',
        'classpath' => 'calendar/externallib.php',
        'type' => 'write',
        'capabilities' => 'moodle/calendar:manageentries, moodle/calendar:manageownentries, moodle/calendar:managegroupentries',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_calendar_get_calendar_events' => array(
        'classname' => 'core_calendar_external',
        'methodname' => 'get_calendar_events',
        'description' => 'Get calendar events',
        'classpath' => 'calendar/externallib.php',
        'type' => 'read',
        'capabilities' => 'moodle/calendar:manageentries, moodle/calendar:manageownentries, moodle/calendar:managegroupentries',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_calendar_get_action_events_by_timesort' => array(
        'classname' => 'core_calendar_external',
        'methodname' => 'get_calendar_action_events_by_timesort',
        'description' => 'Get calendar action events by tiemsort',
        'classpath' => 'calendar/externallib.php',
        'type' => 'read',
        'capabilities' => 'moodle/calendar:manageentries, moodle/calendar:manageownentries, moodle/calendar:managegroupentries',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'readonlysession' => true,
    ),
    'core_calendar_get_action_events_by_course' => array(
        'classname' => 'core_calendar_external',
        'methodname' => 'get_calendar_action_events_by_course',
        'description' => 'Get calendar action events by course',
        'classpath' => 'calendar/externallib.php',
        'type' => 'read',
        'capabilities' => 'moodle/calendar:manageentries, moodle/calendar:manageownentries, moodle/calendar:managegroupentries',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_calendar_get_action_events_by_courses' => array(
        'classname' => 'core_calendar_external',
        'methodname' => 'get_calendar_action_events_by_courses',
        'description' => 'Get calendar action events by courses',
        'classpath' => 'calendar/externallib.php',
        'type' => 'read',
        'capabilities' => 'moodle/calendar:manageentries, moodle/calendar:manageownentries, moodle/calendar:managegroupentries',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_calendar_get_calendar_event_by_id' => array(
        'classname' => 'core_calendar_external',
        'methodname' => 'get_calendar_event_by_id',
        'description' => 'Get calendar event by id',
        'classpath' => 'calendar/externallib.php',
        'type' => 'read',
        'capabilities' => 'moodle/calendar:manageentries, moodle/calendar:manageownentries, moodle/calendar:managegroupentries',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_calendar_submit_create_update_form' => array(
        'classname' => 'core_calendar_external',
        'methodname' => 'submit_create_update_form',
        'description' => 'Submit form data for event form',
        'classpath' => 'calendar/externallib.php',
        'type' => 'write',
        'capabilities' => 'moodle/calendar:manageentries, moodle/calendar:manageownentries, moodle/calendar:managegroupentries',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_calendar_get_calendar_access_information' => array(
        'classname' => 'core_calendar_external',
        'methodname' => 'get_calendar_access_information',
        'description' => 'Convenience function to retrieve some permissions/access information for the given course calendar.',
        'classpath' => 'calendar/externallib.php',
        'type' => 'read',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_calendar_get_allowed_event_types' => array(
        'classname' => 'core_calendar_external',
        'methodname' => 'get_allowed_event_types',
        'description' => 'Get the type of events a user can create in the given course.',
        'classpath' => 'calendar/externallib.php',
        'type' => 'read',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_calendar_get_timestamps' => [
        'classname'     => 'core_calendar_external',
        'methodname'    => 'get_timestamps',
        'description'   => 'Fetch unix timestamps for given date times.',
        'classpath' => 'calendar/externallib.php',
        'type'          => 'read',
        'ajax'          => true,
    ],
    'core_calendar_get_calendar_export_token' => [
        'classname'     => 'core_calendar\external\export\token',
        'description'   => 'Return the auth token required for exporting a calendar.',
        'type'          => 'read',
        'services'      => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ],
    'core_calendar_delete_subscription' => [
        'classname' => 'core_calendar\external\subscription\delete',
        'description' => 'Delete the calendar subscription',
        'type' => 'write',
        'ajax' => true
    ],
    'core_check_get_result_admintree' => [
        'classname' => 'core\check\external\get_result_admintree',
        'description' => 'Executes a check stored in the admin tree and returns the result',
        'type' => 'read',
        'ajax' => true,
        'readonlysession' => true,
    ],
    'core_comment_get_comments' => array(
        'classname' => 'core_comment_external',
        'methodname' => 'get_comments',
        'description' => 'Returns comments.',
        'type' => 'read',
        'capabilities' => 'moodle/comment:view',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_comment_add_comments' => array(
        'classname' => 'core_comment_external',
        'methodname' => 'add_comments',
        'description' => 'Adds a comment or comments.',
        'type' => 'write',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_comment_delete_comments' => array(
        'classname' => 'core_comment_external',
        'methodname' => 'delete_comments',
        'description' => 'Deletes a comment or comments.',
        'type' => 'write',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    ),
    ),
    ),
        'ajax' => true,
    ),
    ),
    ),
    ),
    ),
    // Todo Remove this entry in Moodle 6.0 (MDL-83530).
    ],
    ],
    // Todo Remove this entry in Moodle 6.0 (MDL-83530).
    // Todo Remove this entry in Moodle 6.0 (MDL-83530).
    ),
    ),
    ),
    ),
    ),
    ),
    ),
    ),
    ),
        'readonlysession' => true,
    ),
    ),
    ),
    ],
    ),
    ),
    ],
    ),
    'core_fetch_notifications' => array(
        'classname' => 'core_external',
        'methodname' => 'fetch_notifications',
        'classpath' => 'lib/external/externallib.php',
        'description' => 'Return a list of notifications for the current session',
        'type' => 'read',
        'loginrequired' => false,
        'ajax' => true,
        'readonlysession' => false, // Fetching removes from stack.
    ),
    'core_session_touch' => array(
        'classname' => 'core\session\external',
        'methodname' => 'touch_session',
        'description' => 'Keep the users session alive',
        'type' => 'read',
        'loginrequired' => true,
        'ajax' => true,
    ),
    'core_session_time_remaining' => array(
        'classname' => 'core\session\external',
        'methodname' => 'time_remaining',
        'description' => 'Count the seconds remaining in this session',
        'type' => 'read',
        'loginrequired' => true,
        'ajax' => true,
    ),
    'core_files_get_files' => array(
        'classname' => 'core_files_external',
        'methodname' => 'get_files',
        'description' => 'browse moodle files',
        'type' => 'read',
        'classpath' => 'files/externallib.php',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_files_upload' => array(
        'classname' => 'core_files_external',
        'methodname' => 'upload',
        'description' => 'upload a file to moodle',
        'type'        => 'write',
        'classpath'   => 'files/externallib.php',
    ),
    'core_files_delete_draft_files' => array(
        'classname' => 'core_files\external\delete\draft',
        'description' => 'Delete the indicated files (or directories) from a user draft file area.',
        'type'        => 'write',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_files_get_unused_draft_itemid' => array(
        'classname' => 'core_files\external\get\unused_draft',
        'description' => 'Generate a new draft itemid for the current user.',
        'type'        => 'write',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_form_get_filetypes_browser_data' => array(
        'classname' => 'core_form\external',
        'methodname' => 'get_filetypes_browser_data',
        'classpath' => '',
        'description' => 'Provides data for the filetypes element browser.',
        'type' => 'read',
        'loginrequired' => false,
        'ajax' => true,
    ),
    'core_form_dynamic_form' => array(
        'classname' => 'core_form\external\dynamic_form',
        'description' => 'Process submission of a dynamic (modal) form',
        'type' => 'write',
        'ajax' => true,
    ),
    'core_get_component_strings' => array(
        'classname' => 'core_external',
        'methodname' => 'get_component_strings',
        'classpath' => 'lib/external/externallib.php',
        'description' => 'Return all raw strings (with {$a->xxx}), for a specific component ' .
            '- similar to core get_component_strings(), call',
        'type' => 'read',
        'loginrequired' => false,
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_get_fragment' => array(
        'classname' => 'core_external',
        'methodname' => 'get_fragment',
        'classpath' => 'lib/external/externallib.php',
        'description' => 'Return a fragment for inclusion, such as a JavaScript page.',
        'type' => 'read',
        'ajax' => true,
    ),
    'core_get_string' => array(
        'classname' => 'core_external',
        'methodname' => 'get_string',
        'classpath' => 'lib/external/externallib.php',
        'description' => 'Return a translated string - similar to core get_string(), call',
        'type' => 'read',
        'loginrequired' => false,
        'ajax' => true,
    ),
    'core_get_strings' => array(
        'classname' => 'core_external',
        'methodname' => 'get_strings',
        'classpath' => 'lib/external/externallib.php',
        'description' => 'Return some translated strings - like several core get_string(), calls',
        'type' => 'read',
        'loginrequired' => false,
        'ajax' => true,
    ),
    'core_get_user_dates' => array(
        'classname' => 'core_external',
        'methodname' => 'get_user_dates',
        'classpath' => 'lib/external/externallib.php',
        'description' => 'Return formatted timestamps',
        'type' => 'read',
        'ajax' => true,
    ),
    ],
    ],
    ],
    ],
    ),
    ],
    ],
    ],
    'core_grading_get_definitions' => array(
        'classname' => 'core_grading_external',
        'methodname' => 'get_definitions',
        'description' => 'Get grading definitions',
        'type' => 'read',
    ),
    'core_grading_get_gradingform_instances' => array(
        'classname' => 'core_grading_external',
        'methodname' => 'get_gradingform_instances',
        'description' => 'Get grading form instances',
        'type' => 'read',
    ),
    'core_grading_save_definitions' => array(
        'classname' => 'core_grading_external',
        'methodname' => 'save_definitions',
        'description' => 'Save grading definitions',
        'type' => 'write',
    ),
    ),
    ),
    ),
    ),
    ),
    ],
    'core_message_mute_conversations' => array(
        'classname' => 'core_message_external',
        'methodname' => 'mute_conversations',
        'classpath' => 'message/externallib.php',
        'description' => 'Mutes a list of conversations',
        'type' => 'write',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_message_unmute_conversations' => array(
        'classname' => 'core_message_external',
        'methodname' => 'unmute_conversations',
        'classpath' => 'message/externallib.php',
        'description' => 'Unmutes a list of conversations',
        'type' => 'write',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_message_block_user' => array(
        'classname' => 'core_message_external',
        'methodname' => 'block_user',
        'classpath' => 'message/externallib.php',
        'description' => 'Blocks a user',
        'type' => 'write',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_message_get_contact_requests' => array(
        'classname' => 'core_message_external',
        'methodname' => 'get_contact_requests',
        'classpath' => 'message/externallib.php',
        'description' => 'Returns contact requests for a user',
        'type' => 'read',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_message_create_contact_request' => array(
        'classname' => 'core_message_external',
        'methodname' => 'create_contact_request',
        'classpath' => 'message/externallib.php',
        'description' => 'Creates a contact request',
        'type' => 'write',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_message_confirm_contact_request' => array(
        'classname' => 'core_message_external',
        'methodname' => 'confirm_contact_request',
        'classpath' => 'message/externallib.php',
        'description' => 'Confirms a contact request',
        'type' => 'write',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_message_decline_contact_request' => array(
        'classname' => 'core_message_external',
        'methodname' => 'decline_contact_request',
        'classpath' => 'message/externallib.php',
        'description' => 'Declines a contact request',
        'type' => 'write',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_message_get_received_contact_requests_count' => array(
        'classname' => 'core_message_external',
        'methodname' => 'get_received_contact_requests_count',
        'classpath' => 'message/externallib.php',
        'description' => 'Gets the number of received contact requests',
        'type' => 'read',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_message_delete_contacts' => array(
        'classname' => 'core_message_external',
        'methodname' => 'delete_contacts',
        'classpath' => 'message/externallib.php',
        'description' => 'Remove contacts from the contact list',
        'type' => 'write',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_message_delete_conversations_by_id' => array(
        'classname' => 'core_message_external',
        'methodname' => 'delete_conversations_by_id',
        'classpath' => 'message/externallib.php',
        'description' => 'Deletes a list of conversations.',
        'type' => 'write',
        'capabilities' => 'moodle/site:deleteownmessage',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_message_delete_message' => array(
        'classname' => 'core_message_external',
        'methodname' => 'delete_message',
        'classpath' => 'message/externallib.php',
        'description' => 'Deletes a message.',
        'type' => 'write',
        'capabilities' => 'moodle/site:deleteownmessage',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_message_get_blocked_users' => array(
        'classname' => 'core_message_external',
        'methodname' => 'get_blocked_users',
        'classpath' => 'message/externallib.php',
        'description' => 'Retrieve a list of users blocked',
        'type' => 'read',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_message_data_for_messagearea_search_messages' => array(
        'classname' => 'core_message_external',
        'methodname' => 'data_for_messagearea_search_messages',
        'classpath' => 'message/externallib.php',
        'description' => 'Retrieve the template data for searching for messages',
        'type' => 'read',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_message_message_search_users' => array(
        'classname' => 'core_message_external',
        'methodname' => 'message_search_users',
        'classpath' => 'message/externallib.php',
        'description' => 'Retrieve the data for searching for people',
        'type' => 'read',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_message_get_user_contacts' => array(
        'classname' => 'core_message_external',
        'methodname' => 'get_user_contacts',
        'classpath' => 'message/externallib.php',
        'description' => 'Retrieve the contact list',
        'type' => 'read',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_message_get_conversations' => array(
        'classname' => 'core_message_external',
        'methodname' => 'get_conversations',
        'classpath' => 'message/externallib.php',
        'description' => 'Retrieve a list of conversations for a user',
        'type' => 'read',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'ajax' => true
    ),
    'core_message_get_conversation' => array(
        'classname' => 'core_message_external',
        'methodname' => 'get_conversation',
        'classpath' => 'message/externallib.php',
        'description' => 'Retrieve a conversation for a user',
        'type' => 'read',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'ajax' => true
    ),
    'core_message_get_conversation_between_users' => array(
        'classname' => 'core_message_external',
        'methodname' => 'get_conversation_between_users',
        'classpath' => 'message/externallib.php',
        'description' => 'Retrieve a conversation for a user between another user',
        'type' => 'read',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'ajax' => true
    ),
    'core_message_get_self_conversation' => array(
        'classname' => 'core_message_external',
        'methodname' => 'get_self_conversation',
        'classpath' => 'message/externallib.php',
        'description' => 'Retrieve a self-conversation for a user',
        'type' => 'read',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'ajax' => true
    ),
    'core_message_get_messages' => array(
        'classname' => 'core_message_external',
        'methodname' => 'get_messages',
        'classpath' => 'message/externallib.php',
        'description' => 'Retrieve a list of messages sent and received by a user (conversations, notifications or both)',
        'type' => 'read',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'ajax' => true,
    ),
    'core_message_get_conversation_counts' => array(
        'classname' => 'core_message_external',
        'methodname' => 'get_conversation_counts',
        'classpath' => 'message/externallib.php',
        'description' => 'Retrieve a list of conversation counts, indexed by type.',
        'type' => 'read',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'ajax' => true,
    ),
    'core_message_get_unread_conversation_counts' => array(
        'classname' => 'core_message_external',
        'methodname' => 'get_unread_conversation_counts',
        'classpath' => 'message/externallib.php',
        'description' => 'Retrieve a list of unread conversation counts, indexed by type.',
        'type' => 'read',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'ajax' => true,
    ),
    'core_message_get_conversation_members' => array(
        'classname' => 'core_message_external',
        'methodname' => 'get_conversation_members',
        'classpath' => 'message/externallib.php',
        'description' => 'Retrieve a list of members in a conversation',
        'type' => 'read',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'ajax' => true,
    ),
    'core_message_get_member_info' => array(
        'classname' => 'core_message_external',
        'methodname' => 'get_member_info',
        'classpath' => 'message/externallib.php',
        'description' => 'Retrieve a user message profiles',
        'type' => 'read',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'ajax' => true,
    ),
    'core_message_get_unread_conversations_count' => array(
        'classname' => 'core_message_external',
        'methodname' => 'get_unread_conversations_count',
        'classpath' => 'message/externallib.php',
        'description' => 'Retrieve the count of unread conversations for a given user',
        'type' => 'read',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'readonlysession' => true, // We don't modify the session.
    ),
    'core_message_mark_all_notifications_as_read' => array(
        'classname' => 'core_message_external',
        'methodname' => 'mark_all_notifications_as_read',
        'classpath' => 'message/externallib.php',
        'description' => 'Mark all notifications as read for a given user',
        'type' => 'write',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_message_mark_all_conversation_messages_as_read' => array(
        'classname' => 'core_message_external',
        'methodname' => 'mark_all_conversation_messages_as_read',
        'classpath' => 'message/externallib.php',
        'description' => 'Mark all conversation messages as read for a given user',
        'type' => 'write',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_message_mark_message_read' => array(
        'classname' => 'core_message_external',
        'methodname' => 'mark_message_read',
        'classpath' => 'message/externallib.php',
        'description' => 'Mark a single message as read, trigger message_viewed event.',
        'type' => 'write',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'ajax' => true,
    ),
    'core_message_mark_notification_read' => array(
        'classname' => 'core_message_external',
        'methodname' => 'mark_notification_read',
        'classpath' => 'message/externallib.php',
        'description' => 'Mark a single notification as read, trigger notification_viewed event.',
        'type' => 'write',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'ajax' => true,
    ),
    'core_message_message_processor_config_form' => array(
        'classname' => 'core_message_external',
        'methodname' => 'message_processor_config_form',
        'classpath' => 'message/externallib.php',
        'description' => 'Process the message processor config form',
        'type' => 'write',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_message_get_message_processor' => array(
        'classname' => 'core_message_external',
        'methodname' => 'get_message_processor',
        'classpath' => 'message/externallib.php',
        'description' => 'Get a message processor',
        'type' => 'read',
        'ajax' => true,
    ),
    'core_message_search_contacts' => array(
        'classname' => 'core_message_external',
        'methodname' => 'search_contacts',
        'classpath' => 'message/externallib.php',
        'description' => 'Search for contacts',
        'type' => 'read',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_message_send_instant_messages' => array(
        'classname' => 'core_message_external',
        'methodname' => 'send_instant_messages',
        'classpath' => 'message/externallib.php',
        'description' => 'Send instant messages',
        'type' => 'write',
        'capabilities' => 'moodle/site:sendmessage',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'readonlysession' => true,
    ),
    'core_message_send_messages_to_conversation' => array(
        'classname' => 'core_message_external',
        'methodname' => 'send_messages_to_conversation',
        'classpath' => 'message/externallib.php',
        'description' => 'Send messages to an existing conversation between users',
        'type' => 'write',
        'capabilities' => 'moodle/site:sendmessage',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_message_get_conversation_messages' => array(
        'classname' => 'core_message_external',
        'methodname' => 'get_conversation_messages',
        'classpath' => 'message/externallib.php',
        'description' => 'Retrieve the conversation messages and relevant member information',
        'type' => 'read',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_message_unblock_user' => array(
        'classname' => 'core_message_external',
        'methodname' => 'unblock_user',
        'classpath' => 'message/externallib.php',
        'description' => 'Unblocks a user',
        'type' => 'write',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_message_get_user_notification_preferences' => array(
        'classname' => 'core_message_external',
        'methodname' => 'get_user_notification_preferences',
        'classpath' => 'message/externallib.php',
        'description' => 'Get the notification preferences for a given user.',
        'type' => 'read',
        'capabilities' => 'moodle/user:editownmessageprofile',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_message_get_user_message_preferences' => array(
        'classname' => 'core_message_external',
        'methodname' => 'get_user_message_preferences',
        'classpath' => 'message/externallib.php',
        'description' => 'Get the message preferences for a given user.',
        'type' => 'read',
        'capabilities' => 'moodle/user:editownmessageprofile',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
        'ajax' => true
    ),
    'core_message_set_favourite_conversations' => array(
        'classname' => 'core_message_external',
        'methodname' => 'set_favourite_conversations',
        'classpath' => 'message/externallib.php',
        'description' => 'Mark a conversation or group of conversations as favourites/starred conversations.',
        'type' => 'write',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_message_unset_favourite_conversations' => array(
        'classname' => 'core_message_external',
        'methodname' => 'unset_favourite_conversations',
        'classpath' => 'message/externallib.php',
        'description' => 'Unset a conversation or group of conversations as favourites/starred conversations.',
        'type' => 'write',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_message_delete_message_for_all_users' => array(
        'classname' => 'core_message_external',
        'methodname' => 'delete_message_for_all_users',
        'classpath' => 'message/externallib.php',
        'description' => 'Deletes a message for all users.',
        'type' => 'write',
        'capabilities' => 'moodle/site:deleteanymessage',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_message_get_unread_notification_count' => [
        'classname'     => '\core_message\external\get_unread_notification_count',
        'description'   => 'Get number of unread notifications.',
        'type'          => 'read',
        'services'      => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'core_message_set_default_notification' => [
        'classname'   => 'core_message\external\message_set_default_notification',
        'description' => 'Set the default value for a given notification preference',
        'capabilities' => 'moodle/site:config',
        'type'        => 'write',
        'ajax'        => true,
    ],
    'core_my_view_page' => [
        'classname'     => '\core_my\external\view_page',
        'methodname'    => 'execute',
        'description'   => 'Trigger the My or Dashboard viewed event.',
        'type'          => 'write',
        'services'      => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'core_notes_create_notes' => array(
        'classname' => 'core_notes_external',
        'methodname' => 'create_notes',
        'classpath' => 'notes/externallib.php',
        'description' => 'Create notes',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => 'moodle/notes:manage',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_notes_delete_notes' => array(
        'classname' => 'core_notes_external',
        'methodname' => 'delete_notes',
        'classpath' => 'notes/externallib.php',
        'description' => 'Delete notes',
        'type' => 'write',
        'capabilities' => 'moodle/notes:manage',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_notes_get_course_notes' => array(
        'classname' => 'core_notes_external',
        'methodname' => 'get_course_notes',
        'classpath' => 'notes/externallib.php',
        'description' => 'Returns all notes in specified course (or site), for the specified user.',
        'type' => 'read',
        'capabilities' => 'moodle/notes:view',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_notes_get_notes' => array(
        'classname' => 'core_notes_external',
        'methodname' => 'get_notes',
        'classpath' => 'notes/externallib.php',
        'description' => 'Get notes',
        'type' => 'read',
        'capabilities' => 'moodle/notes:view'
    ),
    'core_notes_update_notes' => array(
        'classname' => 'core_notes_external',
        'methodname' => 'update_notes',
        'classpath' => 'notes/externallib.php',
        'description' => 'Update notes',
        'type' => 'write',
        'capabilities' => 'moodle/notes:manage'
    ),
    'core_notes_view_notes' => array(
        'classname' => 'core_notes_external',
        'methodname' => 'view_notes',
        'classpath' => 'notes/externallib.php',
        'description' => 'Simulates the web interface view of notes/index.php: trigger events.',
        'type' => 'write',
        'capabilities' => 'moodle/notes:view',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_output_load_template' => array(
        'classname' => 'core\output\external',
        'methodname' => 'load_template',
        'description' => 'Load a template for a renderable',
        'type' => 'read',
        'loginrequired' => false,
        'ajax' => true,
    ),
    'core_output_load_template_with_dependencies' => array(
        'classname' => 'core\output\external',
        'methodname' => 'load_template_with_dependencies',
        'description' => 'Load a template and its dependencies for a renderable',
        'type' => 'read',
        'loginrequired' => false,
        'ajax' => true,
    ),
    'core_output_load_fontawesome_icon_system_map' => array(
        'classname' => 'core\external\output\icon_system\load_fontawesome_map',
        'description' => 'Load the mapping of moodle pix names to fontawesome icon names',
        'type' => 'read',
        'loginrequired' => false,
        'ajax' => true,
        'services' => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ),
    // Question related functions.
    'core_question_update_flag' => array(
        'classname'     => 'core_question_external',
        'methodname'    => 'update_flag',
        'description'   => 'Update the flag state of a question attempt.',
        'type'          => 'write',
        'capabilities'  => 'moodle/question:flag',
        'services'      => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_question_get_random_question_summaries' => array(
        'classname' => 'core_question_external',
        'methodname' => 'get_random_question_summaries',
        'description' => 'Get the random question set for a criteria',
        'type' => 'read',
        'ajax' => true,
    ),
    'core_rating_get_item_ratings' => array(
        'classname' => 'core_rating_external',
        'methodname' => 'get_item_ratings',
        'description' => 'Retrieve all the ratings for an item.',
        'type' => 'read',
        'capabilities' => 'moodle/rating:view',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_rating_add_rating' => array(
        'classname' => 'core_rating_external',
        'methodname' => 'add_rating',
        'description' => 'Rates an item.',
        'type' => 'write',
        'capabilities' => 'moodle/rating:rate',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_role_assign_roles' => array(
        'classname' => 'core_role_external',
        'methodname' => 'assign_roles',
        'classpath' => 'enrol/externallib.php',
        'description' => 'Manual role assignments.',
        'type' => 'write',
        'capabilities' => 'moodle/role:assign'
    ),
    'core_role_unassign_roles' => array(
        'classname' => 'core_role_external',
        'methodname' => 'unassign_roles',
        'classpath' => 'enrol/externallib.php',
        'description' => 'Manual role unassignments.',
        'type' => 'write',
        'capabilities' => 'moodle/role:assign'
    ),
    'core_search_get_relevant_users' => array(
        'classname' => '\core_search\external',
        'methodname' => 'get_relevant_users',
        'description' => 'Gets relevant users for a search request.',
        'type' => 'read',
        'ajax' => true
    ),
    'core_search_get_results' => [
        'classname' => '\core_search\external\get_results',
        'description' => 'Get search results.',
        'type' => 'read',
        'capabilities' => 'moodle/search:query',
        'services' => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'core_search_get_search_areas_list' => [
        'classname' => '\core_search\external\get_search_areas_list',
        'description' => 'Get search areas.',
        'type' => 'read',
        'capabilities' => 'moodle/search:query',
        'services' => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'core_search_view_results' => [
        'classname' => '\core_search\external\view_results',
        'description' => 'Trigger view search results event.',
        'type' => 'write',
        'capabilities' => 'moodle/search:query',
        'services' => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'core_search_get_top_results' => [
        'classname' => '\core_search\external\get_top_results',
        'description' => 'Get top search results.',
        'type' => 'read',
        'capabilities' => 'moodle/search:query',
        'services' => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'core_tag_get_tagindex' => array(
        'classname' => 'core_tag_external',
        'methodname' => 'get_tagindex',
        'description' => 'Gets tag index page for one tag and one tag area',
        'type' => 'read',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_tag_get_tags' => array(
        'classname' => 'core_tag_external',
        'methodname' => 'get_tags',
        'description' => 'Gets tags by their ids',
        'type' => 'read',
        'ajax' => true,
    ),
    'core_tag_update_tags' => array(
        'classname' => 'core_tag_external',
        'methodname' => 'update_tags',
        'description' => 'Updates tags',
        'type' => 'write',
        'ajax' => true,
    ),
    'core_tag_get_tagindex_per_area' => array(
        'classname' => 'core_tag_external',
        'methodname' => 'get_tagindex_per_area',
        'description' => 'Gets tag index page per different areas.',
        'type' => 'read',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_tag_get_tag_areas' => array(
        'classname' => 'core_tag_external',
        'methodname' => 'get_tag_areas',
        'description' => 'Retrieves existing tag areas.',
        'type' => 'read',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_tag_get_tag_collections' => array(
        'classname' => 'core_tag_external',
        'methodname' => 'get_tag_collections',
        'description' => 'Retrieves existing tag collections.',
        'type' => 'read',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_tag_get_tag_cloud' => array(
        'classname' => 'core_tag_external',
        'methodname' => 'get_tag_cloud',
        'description' => 'Retrieves a tag cloud for the given collection and/or query search.',
        'type' => 'read',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_update_inplace_editable' => array(
        'classname' => 'core_external',
        'methodname' => 'update_inplace_editable',
        'classpath' => 'lib/external/externallib.php',
        'description' => 'Generic service to update title',
        'type' => 'write',
        'loginrequired' => true,
        'ajax' => true,
    ),
    'core_user_add_user_device' => array(
        'classname' => 'core_user_external',
        'methodname' => 'add_user_device',
        'classpath' => 'user/externallib.php',
        'description' => 'Store mobile user devices information for PUSH Notifications.',
        'type' => 'write',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_user_update_user_device_public_key' => array(
        'classname' => '\core_user\external\update_user_device_public_key',
        'description' => 'Store mobile user public key.',
        'type' => 'write',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_user_add_user_private_files' => array(
        'classname' => 'core_user_external',
        'methodname' => 'add_user_private_files',
        'classpath' => 'user/externallib.php',
        'description' => 'Copy files from a draft area to users private files area.',
        'type' => 'write',
        'capabilities' => 'moodle/user:manageownfiles',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_user_create_users' => array(
        'classname' => 'core_user_external',
        'methodname' => 'create_users',
        'classpath' => 'user/externallib.php',
        'description' => 'Create users.',
        'type' => 'write',
        'capabilities' => 'moodle/user:create'
    ),
    'core_user_delete_users' => array(
        'classname' => 'core_user_external',
        'methodname' => 'delete_users',
        'classpath' => 'user/externallib.php',
        'description' => 'Delete users.',
        'type' => 'write',
        'capabilities' => 'moodle/user:delete'
    ),
    'core_user_get_course_user_profiles' => array(
        'classname' => 'core_user_external',
        'methodname' => 'get_course_user_profiles',
        'classpath' => 'user/externallib.php',
        'description' => 'Get course user profiles (each of the profils matching a course id and a user id),.',
        'type' => 'read',
        'capabilities' => 'moodle/user:viewdetails, moodle/user:viewhiddendetails, moodle/course:useremail, moodle/user:update, '
            . 'moodle/site:accessallgroups',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_user_get_users' => array(
        'classname' => 'core_user_external',
        'methodname' => 'get_users',
        'classpath' => 'user/externallib.php',
        'description' => 'search for users matching the parameters',
        'type' => 'read',
        'capabilities' => 'moodle/user:viewdetails, moodle/user:viewhiddendetails, moodle/course:useremail, moodle/user:update'
    ),
    'core_user_get_users_by_field' => array(
        'classname' => 'core_user_external',
        'methodname' => 'get_users_by_field',
        'classpath' => 'user/externallib.php',
        'description' => 'Retrieve users\' information for a specified unique field - If you want to do a user search, use '
            . 'core_user_get_users() or core_user_search_identity().',
        'type' => 'read',
        'capabilities' => 'moodle/user:viewdetails, moodle/user:viewhiddendetails, moodle/course:useremail, moodle/user:update',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_user_search_identity' => array(
        'classname' => '\core_user\external\search_identity',
        'description' => 'Return list of users identities matching the given criteria in their name or other identity fields.',
        'type' => 'read',
        'capabilities' => 'moodle/user:viewalldetails',
        'ajax' => true,
        'loginrequired' => true,
    ),
    'core_user_remove_user_device' => array(
        'classname' => 'core_user_external',
        'methodname' => 'remove_user_device',
        'classpath' => 'user/externallib.php',
        'description' => 'Remove a user device from the Moodle database.',
        'type' => 'write',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_user_update_users' => array(
        'classname' => 'core_user_external',
        'methodname' => 'update_users',
        'classpath' => 'user/externallib.php',
        'description' => 'Update users.',
        'type' => 'write',
        'capabilities' => 'moodle/user:update',
        'ajax' => true,
    ),
    'core_user_update_user_preferences' => array(
        'classname' => 'core_user_external',
        'methodname' => 'update_user_preferences',
        'classpath' => 'user/externallib.php',
        'description' => 'Update a user\'s preferences',
        'type' => 'write',
        'capabilities' => 'moodle/user:editownmessageprofile, moodle/user:editmessageprofile',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_user_view_user_list' => array(
        'classname' => 'core_user_external',
        'methodname' => 'view_user_list',
        'classpath' => 'user/externallib.php',
        'description' => 'Simulates the web-interface view of user/index.php (triggering events),.',
        'type' => 'write',
        'capabilities' => 'moodle/course:viewparticipants',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_user_view_user_profile' => array(
        'classname' => 'core_user_external',
        'methodname' => 'view_user_profile',
        'classpath' => 'user/externallib.php',
        'description' => 'Simulates the web-interface view of user/view.php and user/profile.php (triggering events),.',
        'type' => 'write',
        'capabilities' => 'moodle/user:viewdetails',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_user_get_user_preferences' => array(
        'classname' => 'core_user_external',
        'methodname' => 'get_user_preferences',
        'classpath' => 'user/externallib.php',
        'description' => 'Return user preferences.',
        'type' => 'read',
        'ajax' => true,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_user_update_picture' => array(
        'classname' => 'core_user_external',
        'methodname' => 'update_picture',
        'classpath' => 'user/externallib.php',
        'description' => 'Update or delete the user picture in the site',
        'type' => 'write',
        'capabilities' => 'moodle/user:editownprofile, moodle/user:editprofile',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_user_set_user_preferences' => array(
        'classname' => 'core_user_external',
        'methodname' => 'set_user_preferences',
        'classpath' => 'user/externallib.php',
        'description' => 'Set user preferences.',
        'type' => 'write',
        'capabilities' => 'moodle/site:config',
        'ajax' => true,
        'loginrequired' => false,
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_user_agree_site_policy' => array(
        'classname' => 'core_user_external',
        'methodname' => 'agree_site_policy',
        'classpath' => 'user/externallib.php',
        'description' => 'Agree the site policy for the current user.',
        'type' => 'write',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_user_get_private_files_info' => array(
        'classname' => 'core_user_external',
        'methodname' => 'get_private_files_info',
        'classpath' => 'user/externallib.php',
        'description' => 'Returns general information about files in the user private files area.',
        'type' => 'read',
        'capabilities' => 'moodle/user:manageownfiles',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_user_prepare_private_files_for_edition' => [
        'classname'     => '\core_user\external\prepare_private_files_for_edition',
        'description'   => 'Prepares the draft area for user private files.',
        'type'          => 'write',
        'capabilities'  => 'moodle/user:manageownfiles',
        'services'      => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'core_user_update_private_files' => [
        'classname'     => '\core_user\external\update_private_files',
        'description'   => 'Copy files from a draft area to users private files area.',
        'type'          => 'write',
        'capabilities'  => 'moodle/user:manageownfiles',
        'services'      => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],

    // Competencies functions.
    ),
    ),
    ),
    ),
    ),
    ),
    ),
    ),
    ),

    'core_webservice_get_site_info' => array(
        'classname' => 'core_webservice_external',
        'methodname' => 'get_site_info',
        'classpath' => 'webservice/externallib.php',
        'description' => 'Return some site info / user info / list web service functions',
        'type' => 'read',
        'services' => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),

    // Blocks functions.
    'core_block_get_course_blocks' => array(
        'classname'     => 'core_block_external',
        'methodname'    => 'get_course_blocks',
        'description'   => 'Returns blocks information for a course.',
        'type'          => 'read',
        'capabilities'  => '',
        'services'      => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),

    'core_block_get_dashboard_blocks' => array(
        'classname'     => 'core_block_external',
        'methodname'    => 'get_dashboard_blocks',
        'description'   => 'Returns blocks information for the given user dashboard.',
        'type'          => 'read',
        'capabilities'  => '',
        'services'      => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),

    'core_block_fetch_addable_blocks' => array(
        'classname'     => 'core_block\external\fetch_addable_blocks',
        'description'   => 'Returns all addable blocks in a given page.',
        'type'          => 'read',
        'capabilities'  => 'moodle/site:manageblocks',
        'ajax'          => true,
        'services'      => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),

    // Filters functions.
    'core_filters_get_available_in_context' => array(
        'classname'   => 'core_filters\external\get_available_in_context',
        'description' => 'Returns the filters available in the given contexts.',
        'type'        => 'read',
        'services'    => array(MOODLE_OFFICIAL_MOBILE_SERVICE),
    ),
    'core_filters_get_all_states' => [
        'classname'   => 'core_filters\external\get_all_states',
        'description' => 'Retrieve all the filters and their states (including overridden ones in any context).',
        'type'        => 'read',
        'services'    => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],

    'core_customfield_delete_field' => array(
        'classname'   => 'core_customfield_external',
        'methodname'  => 'delete_field',
        'classpath'   => 'customfield/externallib.php',
        'description' => 'Deletes an entry',
        'type'        => 'write',
        'ajax'        => true,
    ),
    'core_customfield_reload_template' => array(
        'classname'   => 'core_customfield_external',
        'methodname'  => 'reload_template',
        'classpath'   => 'customfield/externallib.php',
        'description' => 'Reloads template',
        'type'        => 'read',
        'ajax'        => true,
    ),
    'core_customfield_create_category' => array(
        'classname'   => 'core_customfield_external',
        'methodname'  => 'create_category',
        'classpath'   => 'customfield/externallib.php',
        'description' => 'Creates a new category',
        'type'        => 'write',
        'ajax'        => true,
    ),
    'core_customfield_delete_category' => array(
        'classname'   => 'core_customfield_external',
        'methodname'  => 'delete_category',
        'classpath'   => 'customfield/externallib.php',
        'description' => 'Deletes a category',
        'type'        => 'write',
        'ajax'        => true,
    ),
    'core_customfield_move_field'   => array(
        'classname'   => 'core_customfield_external',
        'methodname'  => 'move_field',
        'classpath'   => 'customfield/externallib.php',
        'description' => 'Drag and drop',
        'type'        => 'write',
        'ajax'        => true,
    ),
    'core_customfield_move_category' => array(
        'classname'   => 'core_customfield_external',
        'methodname'  => 'move_category',
        'classpath'   => 'customfield/externallib.php',
        'description' => 'Drag and drop categories',
        'type'        => 'write',
        'ajax'        => true,
    ),
    'core_customfield_toggle_shared' => [
        'classname'   => core_customfield\external\toggle_shared_category::class,
        'methodname'  => 'execute',
        'description' => 'Toggle shared category state',
        'type'        => 'write',
        'ajax'        => true,
    ],
    ],
    'core_table_get_dynamic_table_content' => [
        'classname' => 'core_table\external\dynamic\get',
        'description' => 'Get the dynamic table content raw html',
        'type' => 'read',
        'ajax' => true,
        'services' => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'core_xapi_statement_post' => [
        'classname'     => 'core_xapi\external\post_statement',
        'classpath'     => '',
        'description'   => 'Post an xAPI statement.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => '',
        'services'      => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'core_xapi_post_state' => [
        'classname' => 'core_xapi\external\post_state',
        'classpath' => '',
        'description' => 'Post an xAPI state into an activityId.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => '',
        'services' => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'core_xapi_get_state' => [
        'classname' => 'core_xapi\external\get_state',
        'classpath' => '',
        'description' => 'Get an xAPI state data from an activityId.',
        'type' => 'read',
        'ajax' => true,
        'capabilities' => '',
        'services' => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'core_xapi_get_states' => [
        'classname' => 'core_xapi\external\get_states',
        'description' => 'Get all state ID from an activityId.',
        'type' => 'read',
        'ajax' => true,
        'services' => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'core_xapi_delete_state' => [
        'classname' => 'core_xapi\external\delete_state',
        'classpath' => '',
        'description' => 'Delete an xAPI state data from an activityId.',
        'type' => 'write',
        'ajax' => true,
        'capabilities' => '',
        'services' => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'core_xapi_delete_states' => [
        'classname' => 'core_xapi\external\delete_states',
        'description' => 'Delete all xAPI state data from an activityId.',
        'type' => 'write',
        'ajax' => true,
        'services' => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'core_create_userfeedback_action_record' => [
        'classname'     => 'core\external\record_userfeedback_action',
        'classpath'     => '',
        'description'   => 'Record the action that the user takes in the user feedback notification for future use.',
        'type'          => 'write',
        'ajax'          => true,
        'capabilities'  => '',
    ],
    'core_reportbuilder_filters_reset' => [
        'classname'   => 'core_reportbuilder\external\filters\reset',
        'description' => 'Reset filters for given report',
        'type'        => 'write',
        'ajax'        => true,
    ],
    'core_reportbuilder_set_filters' => [
        'classname'   => 'core_reportbuilder\external\filters\set',
        'description' => 'Set filter values for given report',
        'type'        => 'write',
        'ajax'        => true,
    ],
    'core_dynamic_tabs_get_content' => [
        'classname'   => 'core\external\dynamic_tabs_get_content',
        'description' => 'Returns the content for a dynamic tab',
        'type'        => 'read',
        'ajax'        => true,
    ],
    'core_change_editmode' => [
        'classname'   => 'core\external\editmode',
        'methodname'   => 'change_editmode',
        'description' => 'Change the editing mode',
        'type'        => 'write',
        'ajax'        => true,
    ],
    'core_reportbuilder_reports_delete' => [
        'classname'   => 'core_reportbuilder\external\reports\delete',
        'description' => 'Delete report',
        'type'        => 'write',
        'ajax'        => true,
    ],
    'core_reportbuilder_reports_get' => [
        'classname'   => 'core_reportbuilder\external\reports\get',
        'description' => 'Get custom report',
        'type'        => 'read',
        'ajax'        => true,
    ],
    'core_reportbuilder_list_reports' => [
        'classname'   => 'core_reportbuilder\external\reports\listing',
        'description' => 'List custom reports for current user',
        'type'        => 'read',
        'services'    => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'core_reportbuilder_retrieve_report' => [
        'classname'   => 'core_reportbuilder\external\reports\retrieve',
        'description' => 'Retrieve custom report content',
        'type'        => 'read',
        'services'    => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'core_reportbuilder_retrieve_system_report' => [
        'classname'   => 'core_reportbuilder\external\systemreports\retrieve',
        'description' => 'Retrieve system report content',
        'type'        => 'read',
        'services'    => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'core_reportbuilder_can_view_system_report' => [
        'classname'   => 'core_reportbuilder\external\systemreports\can_view',
        'description' => 'Determine access to a system report',
        'type'        => 'read',
        'services'    => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'core_reportbuilder_view_report' => [
        'classname'   => 'core_reportbuilder\external\reports\view',
        'description' => 'Trigger custom report viewed',
        'type'        => 'write',
        'services'    => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'core_reportbuilder_columns_add' => [
        'classname'   => 'core_reportbuilder\external\columns\add',
        'description' => 'Add column to report',
        'type'        => 'write',
        'ajax'        => true,
    ],
    'core_reportbuilder_columns_delete' => [
        'classname'   => 'core_reportbuilder\external\columns\delete',
        'description' => 'Delete column from report',
        'type'        => 'write',
        'ajax'        => true,
    ],
    'core_reportbuilder_columns_reorder' => [
        'classname'   => 'core_reportbuilder\external\columns\reorder',
        'description' => 'Re-order column within report',
        'type'        => 'write',
        'ajax'        => true,
    ],
    'core_reportbuilder_columns_sort_get' => [
        'classname'   => 'core_reportbuilder\external\columns\sort\get',
        'description' => 'Retrieve column sorting for report',
        'type'        => 'read',
        'ajax'        => true,
    ],
    'core_reportbuilder_columns_sort_reorder' => [
        'classname'   => 'core_reportbuilder\external\columns\sort\reorder',
        'description' => 'Re-order column sorting within report',
        'type'        => 'write',
        'ajax'        => true,
    ],
    'core_reportbuilder_columns_sort_toggle' => [
        'classname'   => 'core_reportbuilder\external\columns\sort\toggle',
        'description' => 'Toggle sorting of column within report',
        'type'        => 'write',
        'ajax'        => true,
    ],
    'core_reportbuilder_conditions_add' => [
        'classname'   => 'core_reportbuilder\external\conditions\add',
        'description' => 'Add condition to report',
        'type'        => 'write',
        'ajax'        => true,
    ],
    'core_reportbuilder_conditions_delete' => [
        'classname'   => 'core_reportbuilder\external\conditions\delete',
        'description' => 'Delete condition from report',
        'type'        => 'write',
        'ajax'        => true,
    ],
    'core_reportbuilder_conditions_reorder' => [
        'classname'   => 'core_reportbuilder\external\conditions\reorder',
        'description' => 'Re-order condition within report',
        'type'        => 'write',
        'ajax'        => true,
    ],
    'core_reportbuilder_conditions_reset' => [
        'classname'   => 'core_reportbuilder\external\conditions\reset',
        'description' => 'Reset conditions for given report',
        'type'        => 'write',
        'ajax'        => true,
    ],
    'core_reportbuilder_filters_add' => [
        'classname'   => 'core_reportbuilder\external\filters\add',
        'description' => 'Add filter to report',
        'type'        => 'write',
        'ajax'        => true,
    ],
    'core_reportbuilder_filters_delete' => [
        'classname'   => 'core_reportbuilder\external\filters\delete',
        'description' => 'Delete filter from report',
        'type'        => 'write',
        'ajax'        => true,
    ],
    'core_reportbuilder_filters_reorder' => [
        'classname'   => 'core_reportbuilder\external\filters\reorder',
        'description' => 'Re-order filter within report',
        'type'        => 'write',
        'ajax'        => true,
    ],
    'core_reportbuilder_audiences_delete' => [
        'classname'   => 'core_reportbuilder\external\audiences\delete',
        'description' => 'Delete audience from report',
        'type'        => 'write',
        'ajax'        => true,
    ],
    'core_reportbuilder_schedules_delete' => [
        'classname'   => 'core_reportbuilder\external\schedules\delete',
        'description' => 'Delete schedule from report',
        'type'        => 'write',
        'ajax'        => true,
    ],
    'core_reportbuilder_schedules_send' => [
        'classname'   => 'core_reportbuilder\external\schedules\send',
        'description' => 'Send report schedule',
        'type'        => 'write',
        'ajax'        => true,
    ],
    'core_reportbuilder_schedules_toggle' => [
        'classname'   => 'core_reportbuilder\external\schedules\toggle',
        'description' => 'Toggle state of report schedule',
        'type'        => 'write',
        'ajax'        => true,
    ],
    'core_admin_set_plugin_state' => [
        'classname' => 'core_admin\external\set_plugin_state',
        'description' => 'Set the state of a plugin',
        'type' => 'write',
        'ajax' => true,
    ],
    'core_admin_set_plugin_order' => [
        'classname' => 'core_admin\external\set_plugin_order',
        'description' => 'Set the order of a plugin',
        'type' => 'write',
        'ajax' => true,
    ],
    'core_admin_set_block_protection' => [
        'classname' => 'core_admin\external\set_block_protection',
        'description' => 'Set the protection state for a block plugin',
        'type' => 'write',
        'ajax' => true,
    ],
    'core_moodlenet_send_activity' => [
        'classname'   => 'core\external\moodlenet_send_activity',
        'description' => 'Send activity to MoodleNet',
        'type'        => 'read',
        'ajax'        => true,
    ],
    'core_moodlenet_get_share_info_activity' => [
        'classname'   => 'core\external\moodlenet_get_share_info_activity',
        'description' => 'Get information about an activity being shared',
        'type'        => 'read',
        'ajax'        => true,
    ],
    'core_moodlenet_auth_check' => [
        'classname'   => 'core\external\moodlenet_auth_check',
        'description' => 'Check a user has authorized for a given MoodleNet site',
        'type'        => 'write',
        'ajax'        => true,
    ],
    'core_moodlenet_get_shared_course_info' => [
        'classname'   => 'core\external\moodlenet_get_shared_course_info',
        'description' => 'Get information about an course being shared',
        'type'        => 'read',
        'ajax'        => true,
    ],
    'core_moodlenet_send_course' => [
        'classname'   => 'core\external\moodlenet_send_course',
        'description' => 'Send course to MoodleNet',
        'type'        => 'read',
        'ajax'        => true,
    ],
    'core_output_poll_stored_progress' => [
        'classname'   => 'core\external\output\poll_stored_progress',
        'methodname'  => 'execute',
        'description' => 'Polls for the current percentage progress of a stored progress object',
        'type'        => 'read',
        'ajax'        => true,
        'readonlysession' => true,
    ],
    'core_ai_delete_provider_instance' => [
        'classname'   => \core_ai\external\delete_provider_instance::class,
        'description' => 'Delete a provider instance',
        'type'        => 'write',
        'ajax'        => true,
    ],
    'core_ai_set_policy_status' => [
        'classname'   => 'core_ai\external\set_policy_status',
        'description' => 'Set a users AI policy acceptance',
        'type'        => 'write',
        'ajax'        => true,
        'services'    => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'core_ai_get_policy_status' => [
        'classname'   => \core_ai\external\get_policy_status::class,
        'description' => 'Get a users AI policy acceptance',
        'type'        => 'read',
        'ajax'        => true,
        'services'    => [MOODLE_OFFICIAL_MOBILE_SERVICE],
    ],
    'core_ai_set_action' => [
        'classname'   => 'core_ai\external\set_action',
        'description' => 'Update action',
        'type'        => 'write',
        'ajax'        => true,
    ],
    'core_ai_set_provider_status' => [
        'classname'   => \core_ai\external\set_provider_status::class,
        'description' => 'Set a providers status',
        'type'        => 'write',
        'ajax'        => true,
    ],
    'core_ai_set_provider_order' => [
        'classname' => \core_ai\external\set_provider_order::class,
        'description' => 'Set the order of a provider',
        'type' => 'write',
        'ajax' => true,
    ],
    'core_sms_set_gateway_status' => [
        'classname'   => 'core_sms\external\sms_gateway_status',
        'description' => 'Set the sms gateway status',
        'type'        => 'write',
        'ajax'        => true,
    ],
    'core_question_move_questions' => [
        'classname' => '\core_question\external\move_questions',
        'description' => 'Bulk move questions to a new category.',
        'type' => 'write',
        'ajax' => true,
    ],
    'core_question_search_shared_banks' => [
        'classname' => '\core_question\external\search_shared_banks',
        'description' => 'Get a list of shared question banks filtered by a search term.',
        'type' => 'read',
        'ajax' => true,
    ],
    'core_message_set_unsent_message' => [
        'classname' => 'core_message\external\set_unsent_message',
        'description' => 'Store an unsent message string',
        'type' => 'write',
        'ajax' => true,
    ],
    'core_message_get_unsent_message' => [
        'classname' => 'core_message\external\get_unsent_message',
        'description' => 'Get an unsent message string',
        'type' => 'read',
        'ajax' => true,
    ],
);

$services = array(
   'Moodle mobile web service'  => array(
        'functions' => array(), // Unused as we add the service in each function definition, third party services would use this.
        'enabled' => 0,
        'restrictedusers' => 0,
        'shortname' => MOODLE_OFFICIAL_MOBILE_SERVICE,
        'downloadfiles' => 1,
        'uploadfiles' => 1
    ),
);
